name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-client:
    runs-on: ubuntu-latest
    name: Generate Angular Client 
    steps:
      - uses: actions/checkout@v2
      - uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-angular
